### PR TITLE
Fix saving the job flags.

### PR DESCRIPTION
**Pull request by sethjackson**
Advanced flags in the update only step weren't saving properly.

This fixes that.

### CODE REVIEW

**Comment by sethjackson** [comment]
I don't really have a use case for it. I just saw that it was broken when I was using the plugin. 

I can update the PR to just remove the options if you want.

**Comment by sethjackson** [comment]
Updated to remove the skip on SCM change option while still leaving the skip on upstream change option.
If the skip on upstream change option is not required I can remove that too.

**Comment by sethjackson** [comment]
Ping.

**Comment by sethjackson** [comment]
Hey any comments on this one? I can remove both flags or leave the skip on upstream change in.

**Comment by sethjackson** [comment]
Any chance of this getting merged?

**Comment by stevespringett** [comment]
Closing as no longer valid

**Pull request closed without merging**
