### PR TITLE
set proxy.nonproxyhosts from Jenkins proxy configuration

### PR DESCRIPTION
**Pull request by thomasgl-orange**
I'm using Jenkins dependency-check plugin in an environment where:
 - all internet access must go through an HTTP proxy
 - we have a local NVD mirror for the CVE databases (an now also one for RetireJS files), which should be accessed directly, bypassing the internet HTTP proxy

The settings currently available in the depcheck plugin (ie., the boolean "Bypass proxy to download NVD data feeds" flag - https://github.com/jenkinsci/dependency-check-plugin/blob/dependency-check-jenkins-plugin-3.3.4/src/main/java/org/jenkinsci/plugins/DependencyCheck/DependencyCheckBuilder.java#L413) doesn't allow me to really configure things correctly:
 - if disabled, internal mirrors are accessed through the HTTP proxy,
 - if enabled, analysers based on internet APIs, like Node Audit Analyzer, are not accessible and thus must be disabled. (which is a bit unexpected actually: the description of the flag makes it look like it is only about requests to NVD, but its effect is broader than that, since implementation consists of not passing any proxy settings to dependency-check when it is enabled)

The obvious solution would be to use a fine grained exclusion list to decide when the proxy must actually be used.  Fortunately, this seems to be already implemented in dependency-check itself:
https://github.com/jeremylong/DependencyCheck/blob/v3.3.4/utils/src/main/java/org/owasp/dependencycheck/utils/URLConnectionFactory.java#L138
It is also already used by the Maven plugin:
https://github.com/jeremylong/DependencyCheck/blob/v3.3.4/maven/src/main/java/org/owasp/dependencycheck/maven/BaseDependencyCheckMojo.java#L1447

In Jenkins, the global proxy configuration has its own exclusions list too, but it is not taken into account by the depcheck plugin.  That's what this PR attempt to fix.

An open question is: does it make sense to keep the boolean flag if this PR gets merged?

### CODE REVIEW

**Comment by thomasgl-orange** [comment]
Oops, force-pushed after stupid copy/paste error in initial commit...

**Comment by stevespringett** [comment]
Thanks for the PR. This feature was introduces at a time when Dependency-Check only relied on the NVD - before NPM Audit and Retire.js was supported. 

We simply cant take the functionality away as it will potentially break integration. IMO, I think we should leave the flag there and put a big DEPRECATED on the label when configuring and refer the user to use the Jenkins global proxy settings instead.

**Comment by thomasgl-orange** [comment]
I have updated the PR with some rewording of the "bypass proxy" option documentation, to make it clear (hopefully) that it is deprecated, and that standard proxy exclusions should be used instead.

**Comment by stevespringett** [comment]
Looks good @thomasgl-orange. Have you tested these changes? I don't have access to a network with a proxy.

**Comment by thomasgl-orange** [comment]
> Have you tested these changes?

Yes, I've done manual tests for a few combinations of mirrors URLs and proxy exceptions rules. Mostly with a local Squid proxy, to check in its logs that what was actually going through the proxy was "right".

Also, my "corporate" test environment is now using a patched plugin, with NVD and Retire.js mirrors on a proxy-excluded internal domain, and it seems to work fine (including actually using the proxy where still required, for the Node Audit analyzer).

What I've not tested (nor modified) is the Nexus and Artifactory analyzers. Both come with their own boolean flags to bypass proxy, which I assume could also be obsoleted by simply using standard proxy exclusions, but I don't have resources to test that.

**Comment by stevespringett** [comment]
Perfect. Thanks for clarification and for the PR!

**Pull request merged**
