### PR TITLE
Add excludes to job options

### PR DESCRIPTION
**Pull request by frydaykg**
Add mechanism that allows to exclude some files and pathes from scan.
Excludes support Ant patter style.

### CODE REVIEW

**Comment by frydaykg** [comment]
Excludes applied to each path or include Ant pattern. It's is not very convinient but I think in most cases excludes contains specific files(specific way) or some extensions, so it shouldn't be a problem.

**Comment by frydaykg** [comment]
Hello @stevespringett!

What do you think about this improvment? Could it be merged? Or It should be developed more?

**Comment by stevespringett** [comment]
DependencyCheckBuilder no longer exists. v5 of the plugin uses the CLI (defined as a Jenkins Global Tool). The CLI already has an `--exclude` option.

**Comment by frydaykg** [comment]
Thank you, look into it.

**Pull request closed without merging**
